backend:
  name: github
  repo: medussion/medussion.github.io
  branch: main

media_folder: public/images/postImage
public_folder: /images/postImage

locale: ko

collections:
  - name: posts
    label: 포스트
    folder: content/posts
    create: true
    delete: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 제목, name: title, widget: string }
      - { label: 공개 여부, name: published, widget: boolean, default: true }
      - { label: 발행일, name: date, widget: datetime, date_format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: 수정일, name: lastmod, widget: datetime, date_format: "YYYY-MM-DDTHH:mm:ssZ", required: false }
      - label: 카테고리
        name: categories
        widget: select
        multiple: true
        options:
          - { label: "C 언어", value: "C" }
          - { label: "C++", value: "Cpp" }
          - { label: "C#", value: "CSharp" }
          - { label: "Unity", value: "Unity" }
          - { label: "디자인 패턴", value: "Design-Pattern" }
          - { label: "Effective C++", value: "Effective-Cpp" }
          - { label: "Effective C#", value: "Effective-CSharp" }
          - { label: "프로젝트", value: "Project" }
          - { label: "세미나", value: "Seminar" }
          - { label: "기타", value: "etc" }
      - { label: 태그, name: tags, widget: list, required: false }
      - { label: 목차 표시, name: toc, widget: boolean, default: true }
      - { label: 본문, name: body, widget: markdown }
